apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-frontend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: healthcare-frontend

  template:
    metadata:
      labels:
        app: healthcare-frontend

    spec:
      containers:
      - name: healthcare-frontend
        image: sbhalsing99/healthcare-frontend:latest
        ports:
        - containerPort: 3000